### PR TITLE
Tc 020.002.001|Privacy and Cookie Policy>Contact us link> Verify redirect from Policy page to Contact form

### PR DESCRIPTION
**Pull request by YuliyaMihaylovaQA**
[https://trello.com/c/JMia3A7B/120-tc020002001-privacy-and-cookie-policycontact-us-link-verify-redirect-from-policy-page-to-contact-form](https://github.com/RedRoverSchool/LumaProjectPython_2024_spring/pull/16)

### CODE REVIEW

**Comment by YuliyaMihaylovaQA** [comment]
[AT_020.002.001| Privacy and Cookie Policy>Contact us link> Verify redirect from Policy page to Contact form](https://trello.com/c/6VKBGt3e/294-at020002001-privacy-and-cookie-policycontact-us-link-verify-redirect-from-policy-page-to-contact-form)

**Review by aqaestuser — APPROVED** [review]
LGTM

**Review by MilaArh — APPROVED** [review]
LGTM

**Comment by YuliyaMihaylovaQA** [comment]
[TC_020.002.001| Privacy and Cookie Policy>Contact us link> Verify redirect from Policy page to Contact form](https://trello.com/c/JMia3A7B/120-tc020002001-privacy-and-cookie-policycontact-us-link-verify-redirect-from-policy-page-to-contact-form)

**Pull request merged**
