### PR TITLE
add  test_mini_cart and test_checkout_cart 

### PR DESCRIPTION
**Pull request by Grom-Zadira85**
('https://trello.com/c/WVaLK93g')
  ('https://trello.com/c/w8Of4GYe')
  ("https://trello.com/c/v4hVrwzq")
   ("https://trello.com/c/p6iExP1c")
("https://trello.com/c/uCZZgQks")
   ("https://trello.com/c/lvLslLGD")
("https://trello.com/c/SQ3op4DX")

### CODE REVIEW

**Review by Lokankara — APPROVED** [review]

**Review by aqaestuser — APPROVED** [review]
LGTM

**Comment by Grom-Zadira85** [comment]
[ТС_005.001.011 | Main page > Cart > View and edit cart > Check color and clickability of "View and edit cart" link in the mini-cart](https://trello.com/c/WVaLK93g/302-%D1%82%D1%81005001011-main-page-cart-view-and-edit-cart-check-color-and-clickability-of-view-and-edit-cart-link-in-the-mini-cart)

**Comment by Grom-Zadira85** [comment]
[ТС_005.001.012 | Main page > Cart > View and edit cart > Сhecking the redirection to the cart page](https://trello.com/c/w8Of4GYe/376-%D1%82%D1%81005001012-main-page-cart-view-and-edit-cart-%D1%81hecking-the-redirection-to-the-cart-page)

**Comment by Grom-Zadira85** [comment]
[ТС_005.001.012 | Main page > Cart > View and edit cart > Сhecking the redirection to the cart page](https://trello.com/c/w8Of4GYe/376-%D1%82%D1%81005001012-main-page-cart-view-and-edit-cart-%D1%81hecking-the-redirection-to-the-cart-page)

**Comment by Grom-Zadira85** [comment]
[ТС_005.001.012 | Main page > Cart > View and edit cart > Сhecking the redirection to the cart page](https://trello.com/c/w8Of4GYe/376-%D1%82%D1%81005001012-main-page-cart-view-and-edit-cart-%D1%81hecking-the-redirection-to-the-cart-page)

**Comment by Grom-Zadira85** [comment]
[ТС_005.001.013| Main page > Cart > View and edit cart > Checking that the size color and product name are correct](https://trello.com/c/v4hVrwzq/381-%D1%82%D1%81005001013-main-page-cart-view-and-edit-cart-checking-that-the-size-color-and-product-name-are-correct)

**Comment by Grom-Zadira85** [comment]
[ТС_005.001.014 | Main page > Cart > View and edit cart  > Checking present price item and Cart Subtotal  in the mini cart](https://trello.com/c/p6iExP1c/382-%D1%82%D1%81005001014-main-page-cart-view-and-edit-cart-checking-present-price-item-and-cart-subtotal-in-the-mini-cart)

**Comment by Grom-Zadira85** [comment]
[ТС_005.001.015| Main page > Cart > View and edit cart > Check the ability to change the quantity of an item and changes price in Cart Subtotal from mini cart](https://trello.com/c/uCZZgQks/383-%D1%82%D1%81005001015-main-page-cart-view-and-edit-cart-check-the-ability-to-change-the-quantity-of-an-item-and-changes-price-in-cart-subt)

**Comment by Grom-Zadira85** [comment]
[ТС_005.001.016| Main page > Cart > View and edit cart  > Checking that the size color  product-image and product name are correct in the Cart page](https://trello.com/c/lvLslLGD/421-%D1%82%D1%81005001016-main-page-cart-view-and-edit-cart-checking-that-the-size-color-product-image-and-product-name-are-correct-in-the-car)

**Comment by Grom-Zadira85** [comment]
[ТС_005.001.017| Main page > Cart > View and edit cart > Check price Quantity and Cart Subtotal present in Cart page](https://trello.com/c/SQ3op4DX/422-%D1%82%D1%81005001017-main-page-cart-view-and-edit-cart-check-price-quantity-and-cart-subtotal-present-in-cart-page)

**Pull request merged**
