### PR TITLE
TC_002.001.010 | Radiant Tee product page > Adding the product to the comparison list

### PR DESCRIPTION
**Pull request by ElenaBarteneva**
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;7Mn9d8Z4">TC_002.001.010 | Radiant Tee product page &gt; Adding the product to the comparison list</a></blockquote>

### CODE REVIEW

**Comment by ElenaBarteneva** [comment]
[TC_002.001.010 | Radiant Tee product page > Adding the product to the comparison list](https://trello.com/c/7Mn9d8Z4/117-tc002001010-radiant-tee-product-page-adding-the-product-to-the-comparison-list)

**Comment by ElenaBarteneva** [comment]
[TC_002.001.010 | Radiant Tee product page > Adding the product to the comparison list](https://trello.com/c/7Mn9d8Z4/117-tc002001010-radiant-tee-product-page-adding-the-product-to-the-comparison-list)

**Comment by ElenaBarteneva** [comment]
[TC_002.001.010 | Radiant Tee product page > Adding the product to the comparison list](https://trello.com/c/7Mn9d8Z4/117-tc002001010-radiant-tee-product-page-adding-the-product-to-the-comparison-list)

**Comment by ElenaBarteneva** [comment]
[TC_002.001.010 | Radiant Tee product page > Adding the product to the comparison list](https://trello.com/c/7Mn9d8Z4/117-tc002001010-radiant-tee-product-page-adding-the-product-to-the-comparison-list)

**Review by omalanova — APPROVED** [review]

**Review by aqaestuser — APPROVED** [review]
LGTM

**Pull request merged**
