### PR TITLE
TC_009.005.004 | Gear catalog > Fitness Equipment > Set of Sprite Yoga Straps > Put set or a few sets of “Sprite Yoga Strap 8 foot” in the cart

### PR DESCRIPTION
**Pull request by Cruz06**
https://trello.com/c/PJ8YNNCm

### CODE REVIEW

**Comment by Cruz06** [comment]
[TC_009.005.004 | Gear catalog > Fitness Equipment > Set of Sprite Yoga Straps > Put set or a few sets of “Sprite Yoga Strap 8 foot” in the cart](https://trello.com/c/PJ8YNNCm/458-tc009005004-gear-catalog-fitness-equipment-set-of-sprite-yoga-straps-put-set-or-a-few-sets-of-sprite-yoga-strap-8-foot-in-the-ca)

**Review by Cruz06 — COMMENTED** [review]
changed nr for second step

**Review by Cruz06 — COMMENTED** [review]
add clear field

**Review by aqaestuser — APPROVED** [review]
LGTM

**Review by Lokankara — APPROVED** [review]

**Pull request merged**
