### PR TITLE
Refactoring Whats New -> Eco Collection New tests

### PR DESCRIPTION
**Pull request by ElenaBarteneva**
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;lbjGjlg5">TC_006.002.001| What&#39;s new &gt; Eco Collection New* &gt; Changing the color in product list</a>
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;E9ZewRUB">TC_006.002.002| What&#39;s new &gt; Eco Collection New* &gt; Visibility of buttons on product card</a>
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;aj3EgeOa">TC_006.002.003 I What&#39;s new &gt; Eco Collection New* &gt; Redirection to the product page by clicking on the image</a>
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;GO8VRlcn">TC_006.002.004 I What&#39;s new &gt; Eco Collection New* &gt; Redirection to the product page by clicking on the product name</a></blockquote>

### CODE REVIEW

**Comment by ElenaBarteneva** [comment]
[TC_006.002.004 I What's new > Eco Collection New* > Redirection to the product page by clicking on the product name](https://trello.com/c/GO8VRlcn/282-tc006002004-i-whats-new-eco-collection-new-redirection-to-the-product-page-by-clicking-on-the-product-name)

**Comment by ElenaBarteneva** [comment]
[TC_006.002.003 I What's new > Eco Collection New* > Redirection to the product page by clicking on the image](https://trello.com/c/aj3EgeOa/281-tc006002003-i-whats-new-eco-collection-new-redirection-to-the-product-page-by-clicking-on-the-image)

**Comment by ElenaBarteneva** [comment]
[TC_006.002.002| What's new > Eco Collection New* > Visibility of buttons on product card](https://trello.com/c/E9ZewRUB/234-tc006002002-whats-new-eco-collection-new-visibility-of-buttons-on-product-card)

**Comment by ElenaBarteneva** [comment]
[TC_006.002.001| What's new > Eco Collection New* > Changing the color in product list](https://trello.com/c/lbjGjlg5/231-tc006002001-whats-new-eco-collection-new-changing-the-color-in-product-list)

**Review by AndZhelBack — APPROVED** [review]

**Review by KatyaMy — APPROVED** [review]

**Pull request merged**
