### PR TITLE
RF | Refactor to new requirements(Training Page)

### PR DESCRIPTION
**Pull request by KatyaMy**
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;fkmwz6Ok">RF_010.003 | Training &gt; Category &quot;Video Download&quot; &gt; Visibility, clickability, redirection</a></blockquote>

<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;TbvtUfVi">RF_010.004 | Training &gt; Block 1 ( &quot;Block-promo training-main&quot;) &gt; Visibility</a></blockquote>

### CODE REVIEW

**Comment by KatyaMy** [comment]
[RF_010.003 | Training > Category "Video Download" > Visibility, clickability, redirection](https://trello.com/c/fkmwz6Ok/480-rf010003-training-category-video-download-visibility-clickability-redirection)

**Comment by KatyaMy** [comment]
[RF_010.004 | Training > Block 1 ( "Block-promo training-main") > Visibility](https://trello.com/c/TbvtUfVi/481-rf010004-training-block-1-block-promo-training-main-visibility)

**Comment by KatyaMy** [comment]
[Merge branch **'refs/heads/main'** into RF_010.003]

**Review by Lokankara — APPROVED** [review]

**Review by aqaestuser — APPROVED** [review]
LGTM

**Comment by aqaestuser** [comment]
> refs/heads/main

не знаю я чего гит решил полный путь написать вдруг

**Pull request merged**
