### PR TITLE
TC_005.001.006 | Main page > Cart > Proceed to Checkout via shopping cart

### PR DESCRIPTION
**Pull request by vguliakin**
https://trello.com/c/nBYV0Aum/208-tc005001006-main-page-cart-proceed-to-checkout-via-shopping-cart

### CODE REVIEW

**Comment by vguliakin** [comment]
Походу тесты у кого то полетели? Мои прошли вроде как без проблем

**Comment by KatyaMy** [comment]
Забыл карточку Trello

**Comment by vguliakin** [comment]
Залил

**Comment by KatyaMy** [comment]
[TC_005.001.006 | Main page > Cart > Proceed to Checkout via shopping cart](https://trello.com/c/nBYV0Aum/208-tc005001006-main-page-cart-proceed-to-checkout-via-shopping-cart)

**Pull request closed without merging**
