### PR TITLE
TC_006.008.002 | What's new > Performance Sportswear New > 3 tests

### PR DESCRIPTION
**Pull request by Cruz06**
https://trello.com/c/cmwZ3A6P
https://trello.com/c/WjUokO7r
https://trello.com/c/dYQgmbfJ

### CODE REVIEW

**Review by aqaestuser — APPROVED** [review]
LGTM

**Review by verafes — APPROVED** [review]

**Comment by Cruz06** [comment]
[TC_006.008.002 | What's new > Performance Sportswear New > Clicking on button "Add to Cart" in the catalog without selecting the color and size of the product prevoiusly](https://trello.com/c/cmwZ3A6P/262-tc006008002-whats-new-performance-sportswear-new-clicking-on-button-add-to-cart-in-the-catalog-without-selecting-the-color-and-s)

**Comment by Cruz06** [comment]
[TC_006.008.003 | What's new > Performance Sportswear New > Color and measure can be choose](https://trello.com/c/WjUokO7r/263-tc006008003-whats-new-performance-sportswear-new-color-and-measure-can-be-choose)

**Comment by Cruz06** [comment]
[TC_006.008.004 | What's new > Performance Sportswear New > Click button "Add to Cart" in the product card without selecting color and measure](https://trello.com/c/dYQgmbfJ/264-tc006008004-whats-new-performance-sportswear-new-click-button-add-to-cart-in-the-product-card-without-selecting-color-and-measur)

**Pull request merged**
