### PR TITLE
Refactoring Radiant tee product tests

### PR DESCRIPTION
**Pull request by ElenaBarteneva**

### CODE REVIEW

**Comment by ElenaBarteneva** [comment]
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;SKLAh5ku">TC_002.001.001 | Radiant Tee product page &gt; Visibility of product name, price and photo</a></blockquote>
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;xGtHnQaq">TC_002.001.002 | Radiant Tee product page &gt; Add to cart &gt; Adding the product to cart</a></blockquote>
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;mtsK5CPx">TC_002.001.003 | Radiant Tee product page &gt; Quantity of items&gt; Quantity of items added to cart</a></blockquote>
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;EXhjde1P">TC_002.001.004 | Radiant Tee product page &gt; Visibility of the product description and detailed information</a></blockquote>
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;PChP2lY4">TC_002.001.005 | Radiant Tee product page &gt; Reviews &gt; Reviews visibility</a></blockquote>
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;5xoWR2Ef">TC_002.001.007 | Radiant Tee product page &gt; Product parameters &gt; Changing the product size</a></blockquote>
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;IR9y4zwY">TC_002.001.009 | Radiant Tee product page &gt; Adding the product to the wish list</a></blockquote>

**Comment by ElenaBarteneva** [comment]
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;SKLAh5ku">TC_002.001.001 | Radiant Tee product page &gt; Visibility of product name, price and photo</a></blockquote>
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;xGtHnQaq">TC_002.001.002 | Radiant Tee product page &gt; Add to cart &gt; Adding the product to cart</a></blockquote>
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;mtsK5CPx">TC_002.001.003 | Radiant Tee product page &gt; Quantity of items&gt; Quantity of items added to cart</a></blockquote>
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;EXhjde1P">TC_002.001.004 | Radiant Tee product page &gt; Visibility of the product description and detailed information</a></blockquote>
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;PChP2lY4">TC_002.001.005 | Radiant Tee product page &gt; Reviews &gt; Reviews visibility</a></blockquote>
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;5xoWR2Ef">TC_002.001.007 | Radiant Tee product page &gt; Product parameters &gt; Changing the product size</a></blockquote>
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;IR9y4zwY">TC_002.001.009 | Radiant Tee product page &gt; Adding the product to the wish list</a></blockquote>

**Review by gurinowicz — APPROVED** [review]

**Comment by ElenaBarteneva** [comment]
[TC_002.001.005 | Radiant Tee product page > Reviews > Reviews visibility](https://trello.com/c/PChP2lY4/108-tc002001005-radiant-tee-product-page-reviews-reviews-visibility)

**Comment by ElenaBarteneva** [comment]
[TC_002.001.001 | Radiant Tee product page > Visibility of product name, price and photo](https://trello.com/c/SKLAh5ku/103-tc002001001-radiant-tee-product-page-visibility-of-product-name-price-and-photo)

**Comment by ElenaBarteneva** [comment]
[TC_002.001.002 | Radiant Tee product page > Add to cart > Adding the product to cart](https://trello.com/c/xGtHnQaq/104-tc002001002-radiant-tee-product-page-add-to-cart-adding-the-product-to-cart)

**Comment by ElenaBarteneva** [comment]
[TC_002.001.002 | Radiant Tee product page > Add to cart > Adding the product to cart](https://trello.com/c/xGtHnQaq/104-tc002001002-radiant-tee-product-page-add-to-cart-adding-the-product-to-cart)

**Comment by ElenaBarteneva** [comment]
[TC_002.001.003 | Radiant Tee product page > Quantity of items> Quantity of items added to cart](https://trello.com/c/mtsK5CPx/105-tc002001003-radiant-tee-product-page-quantity-of-items-quantity-of-items-added-to-cart)

**Comment by ElenaBarteneva** [comment]
[TC_002.001.007 | Radiant Tee product page > Product parameters > Changing the product size](https://trello.com/c/5xoWR2Ef/110-tc002001007-radiant-tee-product-page-product-parameters-changing-the-product-size)

**Comment by ElenaBarteneva** [comment]
[TC_002.001.009 | Radiant Tee product page > Adding the product to the wish list](https://trello.com/c/IR9y4zwY/113-tc002001009-radiant-tee-product-page-adding-the-product-to-the-wish-list)

**Comment by ElenaBarteneva** [comment]
[TC_002.001.009 | Radiant Tee product page > Adding the product to the wish list](https://trello.com/c/IR9y4zwY/113-tc002001009-radiant-tee-product-page-adding-the-product-to-the-wish-list)

**Pull request merged**
